<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title><?= isset($title) ? $title : 'Área Administrativa'?></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="<?= PATH?>/bootstrap-3.3.7-dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= PATH?>/public/css/estiloADM.css">
    <link href="<?= PATH?>/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- FullCalendar -->
    <link href='<?= PATH?>/public/css/fullcalendar.css' rel='stylesheet' />

</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Opp</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#" alt="home">Home</a></li>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?= PATH ?>/admin/logout">&raquo; Sair</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>