<body>

<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">


            <div class="inner cover">
                <h1 class="cover-heading">Benvindo ao Calendário OPP.</h1>
                <p class="lead">Este é o calendário OPP onde você dinamiza e expõe seus eventos e data de maneira geral, a ser compartilhada e observada por todos a que tem o modo de exibição.</p>
                <p class="lead">
                    <a href="#" class="btn btn-lg btn-secondary">Observatório</a>
                </p>
            </div>
        </div>
    </div>

</div>
</body>
